export const actionSchema = {
  GEN_WORLD: { type: "object", shape: {} },
  CONFIRM_FOUNDATION: { type: "object", shape: {} },
  CONFIRM_CORE_ZONE: { type: "object", shape: {} },
  TOGGLE_DNA_ZONE_WORKER: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, remove: { type: "boolean" } } },
  BUILD_INFRA_PATH: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, remove: { type: "boolean" } } },
  TOGGLE_RUNNING: { type: "object", shape: { running: { type: "boolean" } } },
  SIM_STEP: { type: "object", shape: {} },
  SET_SPEED: { type: "object", shape: { speed: { type: "number" } } },
  SET_SEED: { type: "object", shape: { seed: { type: "string" } } },
  SET_SIZE: { type: "object", shape: { w: { type: "number" }, h: { type: "number" } } },
  SET_MAPSPEC: {
    type: "object",
    shape: {
      mapSpec: {
        type: "object",
        shape: {
          name: { type: "string", default: "", maxLen: 128 },
          gridW: { type: "number", min: 1, max: 512, int: true },
          gridH: { type: "number", min: 1, max: 512, int: true },
          tileSize: { type: "number", min: 1, max: 512, int: true },
          presetId: { type: "string", default: "", maxLen: 128 },
        },
      },
    },
  },
  SET_MAP_TILE: {
    type: "object",
    shape: {
      x: { type: "number" },
      y: { type: "number" },
      mode: { type: "string" },
      value: { type: "number" },
      remove: { type: "boolean" },
    },
  },
  SET_SURFACE_TILE: {
    type: "object",
    shape: {
      tiles: { type: "object" },
      surfaceType: { type: "string" },
      brushSize: { type: "number" },
    },
  },
  SET_RESOURCE_TILE: {
    type: "object",
    shape: {
      tiles: { type: "object" },
      resourceKind: { type: "string" },
      resourceStage: { type: "string" },
      brushSize: { type: "number" },
    },
  },
  ERASE_TILE_CONTENT: {
    type: "object",
    shape: {
      tiles: { type: "object" },
      layer: { type: "string" },
      brushSize: { type: "number" },
    },
  },
  BUILDER_UNDO: { type: "object", shape: {} },
  BUILDER_REDO: { type: "object", shape: {} },
  SET_BUILDER_BRUSH_SIZE: {
    type: "object",
    shape: {
      size: { type: "number" },
    },
  },
  GENERATE_MAP_SEED: { type: "object", shape: {} },
  SET_RENDER_MODE: { type: "object", shape: {}, allowUnknown: true },
  SET_PHYSICS: { type: "object", shape: {}, allowUnknown: true },
  SET_BRUSH: { type: "object", shape: {}, allowUnknown: true },
  SET_UI: { type: "object", shape: {}, allowUnknown: true },
  SET_GLOBAL_LEARNING: { type: "object", shape: {}, allowUnknown: true },
  RESET_GLOBAL_LEARNING: { type: "object", shape: {} },
  SET_TILE: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, radius: { type: "number" }, value: { type: "number" }, clear: { type: "boolean" }, mode: { type: "string" } }, allowUnknown: true },
  SELECT_ENTITY: { type: "object", shape: { entityKind: { type: "string" }, entityId: { type: "string" } } },
  PLACE_WORKER: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, remove: { type: "boolean" } } },
  ISSUE_MOVE: { type: "object", shape: { entityId: { type: "string" }, targetX: { type: "number" }, targetY: { type: "number" } } },
  PLACE_CORE: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, remove: { type: "boolean" } } },
  PLACE_BUILDING: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, buildingKind: { type: "string" }, facing: { type: "string" } } },
  PLACE_BELT_SEGMENT: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, direction: { type: "string" }, remove: { type: "boolean" } } },
  PLACE_LINE_SEGMENT: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, remove: { type: "boolean" } } },
  SET_CORE_ROUTING: { type: "object", shape: { coreId: { type: "string" }, resourceKind: { type: "string" } } },
  QUEUE_WORKER: { type: "object", shape: { coreId: { type: "string" }, count: { type: "number" } } },
  SPAWN_FIGHTER: { type: "object", shape: { coreId: { type: "string" }, workerId: { type: "string" }, topologyClass: { type: "string" } } },
  ASSIGN_REPAIR: { type: "object", shape: { workerId: { type: "string" }, targetX: { type: "number" }, targetY: { type: "number" } } },
  PLACE_SPLIT_CLUSTER: { type: "object", shape: { x: { type: "number" }, y: { type: "number" } } },
  HARVEST_WORKER: { type: "object", shape: { x: { type: "number" }, y: { type: "number" } } },
  SET_ZONE: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, radius: { type: "number" }, zoneType: { type: "number" } } },
  SET_MUTATOR_PATTERN: { type: "object", shape: { mutatorId: { type: "string" } }, allowUnknown: true },
  COMMIT_MUTATION: { type: "object", shape: { mutatorId: { type: "string" }, topologyClass: { type: "string" } }, allowUnknown: true },
  SET_WIN_MODE: { type: "object", shape: { winMode: { type: "string" } } },
};
