export const LEGACY_ACTION_REPLACEMENTS = Object.freeze({
  CONFIRM_FOUNDATION: "PLACE_CORE",
  CONFIRM_CORE_ZONE: "PLACE_CORE",
  TOGGLE_DNA_ZONE_WORKER: "PLACE_BUILDING",
  BUILD_INFRA_PATH: "PLACE_LINE_SEGMENT",
  SET_BRUSH: "SELECT_ENTITY",
  PLACE_SPLIT_CLUSTER: "PLACE_BUILDING",
  HARVEST_WORKER: "QUEUE_WORKER",
  SET_ZONE: "PLACE_BUILDING",
});

export const LEGACY_ACTIONS = Object.freeze(Object.keys(LEGACY_ACTION_REPLACEMENTS));

export function isLegacyActionType(type) {
  return Object.prototype.hasOwnProperty.call(LEGACY_ACTION_REPLACEMENTS, type);
}
