import {
  BRUSH_MODE,
  GAME_RESULT,
  GOAL_CODE,
  OVERLAY_MODE,
  RUN_PHASE,
  WIN_MODE,
} from "./ids.js";

export const stateSchema = {
  type: "object",
  shape: {
    meta: {
      type: "object",
      shape: {
        seed: { type: "string", default: "life-light" },
        gridW: { type: "number", default: 16 },
        gridH: { type: "number", default: 16 },
        speed: { type: "number", default: 24 },
        contractProfile: { type: "string", default: "lifegamelab_rts_v1_1" },
        migrationSlice: { type: "string", default: "slice_b_mapspec" },
        brushMode: { type: "string", default: BRUSH_MODE.OBSERVE },
        brushRadius: { type: "number", default: 3 },
        renderMode: { type: "string", default: "combined" },
        activeOverlay: { type: "string", default: OVERLAY_MODE.NONE },
        worldPresetId: { type: "string", default: "river_delta" },
        physics: { type: "object", shape: {}, allowUnknown: true },
        ui: {
          type: "object",
          shape: {
            panelOpen: { type: "boolean", default: false },
            activeTab: { type: "string", default: "lage" },
            expertMode: { type: "boolean", default: false },
            showBiochargeOverlay: { type: "boolean", default: false },
            showRemoteAttackOverlay: { type: "boolean", default: true },
            showDefenseOverlay: { type: "boolean", default: true },
            offscreenEnabled: { type: "boolean", default: false },
            renderDetailMode: { type: "string", default: "auto" },
            ariaLevel: { type: "number", default: 1 },
          },
        },
        globalLearning: {
          type: "object",
          default: {
            enabled: false,
            strength: 0.42,
            bank: {
              light: 0.5,
              nutrient: 0.5,
              toxin: 0.5,
              resilience: 0.5,
              energySense: 0.5,
              toxinMetabolism: 0.0,
              stage: 1,
              xp: 0,
              mutationScore: 0,
              samples: 0,
              updates: 0,
            },
          },
          shape: {},
          allowUnknown: true,
        },
        devMutationVault: { type: "object", shape: {}, allowUnknown: true },
        playerLineageId: { type: "number", default: 0 },
        cpuLineageId: { type: "number", default: 0 },
        placementCostEnabled: { type: "boolean", default: true },
        simStepCount: { type: "number", default: 0 },
      },
    },
    map: {
      type: "object",
      shape: {
        activeSource: { type: "string", default: "legacy_preset" },
        compiledHash: { type: "string", default: "" },
        spec: {
          type: "object",
          default: { version: "gdd_v1_1", mode: "manual" },
          shape: {
            surfacePlan: { type: "object", default: {}, shape: {}, allowUnknown: true },
            resourcePlan: { type: "object", default: {}, shape: {}, allowUnknown: true },
            generatedSeed: { type: "string", default: "" },
          },
          allowUnknown: true,
        },
        validation: {
          type: "object",
          default: { status: "uncompiled", issueCount: 0, summary: "slice_a_scaffold" },
          shape: {
            status: { type: "string", default: "uncompiled" },
            issueCount: { type: "number", default: 0 },
            summary: { type: "string", default: "awaiting_mapspec_compile" },
          },
        },
      },
    },
    world: { type: "object", shape: {}, allowUnknown: true },
    sim: {
      type: "object",
      shape: {
        tick: { type: "number", default: 0 },
        running: { type: "boolean", default: false },
        runPhase: { type: "string", default: RUN_PHASE.GENESIS_SETUP },
        phase0PlantsDelivered: { type: "number", default: 0 },
        phase0CorePlaced: { type: "boolean", default: false },
        queuedWorkerCount: { type: "number", default: 0 },
        deprecatedActionMode: { type: "boolean", default: true },
        founderBudget: { type: "number", default: 1 },
        founderPlaced: { type: "number", default: 0 },
        selectedUnit: { type: "number", default: -1 },
        selectedEntity: {
          type: "object",
          default: { entityKind: "", entityId: "" },
          shape: {
            entityKind: { type: "string", default: "" },
            entityId: { type: "string", default: "" },
          },
        },
        unitOrder: {
          type: "object",
          default: { active: false, fromX: -1, fromY: -1, targetX: -1, targetY: -1 },
          shape: {
            active: { type: "boolean", default: false },
            fromX: { type: "number", default: -1 },
            fromY: { type: "number", default: -1 },
            targetX: { type: "number", default: -1 },
            targetY: { type: "number", default: -1 },
          },
        },
        activeOrder: {
          type: "object",
          default: {
            active: false,
            type: "",
            fromX: -1,
            fromY: -1,
            targetX: -1,
            targetY: -1,
            progress: 0,
            maxProgress: 120,
          },
          shape: {
            active: { type: "boolean", default: false },
            type: { type: "string", default: "" },
            fromX: { type: "number", default: -1 },
            fromY: { type: "number", default: -1 },
            targetX: { type: "number", default: -1 },
            targetY: { type: "number", default: -1 },
            progress: { type: "number", default: 0 },
            maxProgress: { type: "number", default: 120 },
          },
        },
        mutatorDraft: {
          type: "object",
          default: { mutatorId: "", topologyClass: "", nodeCount: 0, closed: false },
          shape: {
            mutatorId: { type: "string", default: "" },
            topologyClass: { type: "string", default: "" },
            nodeCount: { type: "number", default: 0 },
            closed: { type: "boolean", default: false },
          },
        },
        lastCommand: { type: "string", default: "" },
        lastAutoAction: { type: "string", default: "" },
        unlockedZoneTier: { type: "number", default: 0 },
        nextZoneUnlockKind: { type: "string", default: "" },
        nextZoneUnlockCostEnergy: { type: "number", default: 0 },
        zoneUnlockProgress: { type: "number", default: 0 },
        coreEnergyStableTicks: { type: "number", default: 0 },
        zone2Unlocked: { type: "boolean", default: false },
        zone2PlacementBudget: { type: "number", default: 0 },
        dnaZoneCommitted: { type: "boolean", default: false },
        nextInfraUnlockCostDNA: { type: "number", default: 0 },
        infrastructureUnlocked: { type: "boolean", default: false },
        infraBuildMode: { type: "string", default: "" },
        infraBuildCostEnergy: { type: "number", default: 0 },
        infraBuildCostDNA: { type: "number", default: 0 },
        cpuBootstrapDone: { type: "number", default: 0 },
        aliveCount: { type: "number", default: 0 },
        aliveRatio: { type: "number", default: 0 },
        meanLAlive: { type: "number", default: 0 },
        meanEnergyAlive: { type: "number", default: 0 },
        meanReserveAlive: { type: "number", default: 0 },
        meanNutrientField: { type: "number", default: 0 },
        meanToxinField: { type: "number", default: 0 },
        meanSaturationField: { type: "number", default: 0 },
        meanPlantField: { type: "number", default: 0 },
        meanBiochargeField: { type: "number", default: 0 },
        meanWaterField: { type: "number", default: 0 },
        plantTileRatio: { type: "number", default: 0 },
        dominantHueRatio: { type: "number", default: 0 },
        lineageDiversity: { type: "number", default: 0 },
        evolutionStageMean: { type: "number", default: 1 },
        evolutionStageMax: { type: "number", default: 1 },
        networkRatio: { type: "number", default: 0 },
        clusterRatio: { type: "number", default: 0 },
        birthsLastStep: { type: "number", default: 0 },
        deathsLastStep: { type: "number", default: 0 },
        mutationsLastStep: { type: "number", default: 0 },
        raidEventsLastStep: { type: "number", default: 0 },
        infectionsLastStep: { type: "number", default: 0 },
        conflictKillsLastStep: { type: "number", default: 0 },
        superCellsLastStep: { type: "number", default: 0 },
        remoteAttacksLastStep: { type: "number", default: 0 },
        remoteAttackKillsLastStep: { type: "number", default: 0 },
        defenseActivationsLastStep: { type: "number", default: 0 },
        resourceStolenLastStep: { type: "number", default: 0 },
        plantsPrunedLastStep: { type: "number", default: 0 },
        cellPatternCounts: {
          type: "object",
          default: { line: 0, angle: 0, triangle: 0, loop: 0 },
          shape: {},
          allowUnknown: true,
        },
        nutrientCappedTilesLastStep: { type: "number", default: 0 },
        energyClearedTilesLastStep: { type: "number", default: 0 },
        expansionCount: { type: "number", default: 0 },
        lastExpandTick: { type: "number", default: -99999 },
        expansionWork: { type: "number", default: 0 },
        nextExpandCost: { type: "number", default: 120 },
        playerAliveCount: { type: "number", default: 0 },
        cpuAliveCount: { type: "number", default: 0 },
        playerEnergyIn: { type: "number", default: 0 },
        playerEnergyOut: { type: "number", default: 0 },
        playerEnergyNet: { type: "number", default: 0 },
        playerEnergyStored: { type: "number", default: 0 },
        lightShare: { type: "number", default: 0 },
        nutrientShare: { type: "number", default: 0 },
        seasonPhase: { type: "number", default: 0 },
        playerDNA: { type: "number", default: 0 },
        totalHarvested: { type: "number", default: 0 },
        playerStage: { type: "number", default: 1 },
        stageProgressScore: { type: "number", default: 0 },
        harvestYieldTotal: { type: "number", default: 0 },
        pruneYieldTotal: { type: "number", default: 0 },
        recycleYieldTotal: { type: "number", default: 0 },
        seedYieldTotal: { type: "number", default: 0 },
        stabilityScore: { type: "number", default: 0 },
        ecologyScore: { type: "number", default: 0 },
        activeBiomeCount: { type: "number", default: 0 },
        patternCatalog: { type: "object", default: {}, shape: {}, allowUnknown: true },
        patternBonuses: {
          type: "object",
          default: {
            energy: 0,
            dna: 0,
            stability: 0,
            vision: 0,
            defense: 0,
            transport: 0,
          },
          shape: {},
          allowUnknown: true,
        },
        energySupremacyTicks: { type: "number", default: 0 },
        efficiencyTicks: { type: "number", default: 0 },
        lossStreakTicks: { type: "number", default: 0 },
        stockpileTicks: { type: "number", default: 0 },
        cpuEnergyIn: { type: "number", default: 0 },
        gameResult: { type: "string", default: GAME_RESULT.NONE },
        winMode: { type: "string", default: WIN_MODE.SUPREMACY },
        gameEndTick: { type: "number", default: 0 },
        runSummary: {
          type: "object",
          default: {
            result: "",
            winMode: "",
            tick: 0,
            stage: 1,
            seed: "",
            cpuDelta: 0,
            playerDNA: 0,
            playerEnergyNet: 0,
            totalHarvested: 0,
            activeBiomeCount: 0,
            dominantTopology: "none",
            nextSeedSuggestion: "",
            score: 0,
          },
          shape: {
            result: { type: "string", default: "" },
            winMode: { type: "string", default: "" },
            tick: { type: "number", default: 0 },
            stage: { type: "number", default: 1 },
            seed: { type: "string", default: "" },
            cpuDelta: { type: "number", default: 0 },
            playerDNA: { type: "number", default: 0 },
            playerEnergyNet: { type: "number", default: 0 },
            totalHarvested: { type: "number", default: 0 },
            activeBiomeCount: { type: "number", default: 0 },
            dominantTopology: { type: "string", default: "none" },
            nextSeedSuggestion: { type: "string", default: "" },
            score: { type: "number", default: 0 },
          },
        },
        goal: { type: "string", default: GOAL_CODE.HARVEST_SECURE },
      },
    },
  },
};
