export {
  SURFACE_TYPE,
  SURFACE_TYPE_VALUES,
  RESOURCE_KIND_BUILDER,
  RESOURCE_KIND_BUILDER_VALUES,
  RESOURCE_STAGE,
  SURFACE_TYPE_LABEL,
  RESOURCE_KIND_BUILDER_LABEL,
} from "../sim/mapBuilderResources.js";
