export const actionSchema = {
  GEN_WORLD: { type: "object", shape: {} },
  CONFIRM_FOUNDATION: { type: "object", shape: {} },
  CONFIRM_CORE_ZONE: { type: "object", shape: {} },
  START_DNA_ZONE_SETUP: { type: "object", shape: {} },
  TOGGLE_DNA_ZONE_CELL: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, remove: { type: "boolean" } } },
  CONFIRM_DNA_ZONE: { type: "object", shape: {} },
  BEGIN_INFRA_BUILD: { type: "object", shape: {} },
  BUILD_INFRA_PATH: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, remove: { type: "boolean" } } },
  CONFIRM_INFRA_PATH: { type: "object", shape: {} },
  TOGGLE_RUNNING: { type: "object", shape: { running: { type: "boolean" } } },
  SIM_STEP: { type: "object", shape: {} },
  SET_SPEED: { type: "number" },
  SET_SEED: { type: "string" },
  SET_SIZE: { type: "object", shape: { w: { type: "number" }, h: { type: "number" } } },
  SET_WORLD_PRESET: { type: "object", shape: { presetId: { type: "string" } } },
  SET_MAPSPEC: { type: "object", shape: { mapSpec: { type: "object", shape: {}, allowUnknown: true } } },
  SET_RENDER_MODE: { type: "string" },
  SET_PHYSICS: { type: "object", shape: {}, allowUnknown: true },
  SET_BRUSH: { type: "object", shape: {}, allowUnknown: true },
  SET_UI: { type: "object", shape: {}, allowUnknown: true },
  SET_GLOBAL_LEARNING: { type: "object", shape: {}, allowUnknown: true },
  RESET_GLOBAL_LEARNING: { type: "object", shape: {} },
  SET_TILE: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, radius: { type: "number" }, value: { type: "number" }, clear: { type: "boolean" }, mode: { type: "string" } }, allowUnknown: true },
  SELECT_ENTITY: { type: "object", shape: { entityKind: { type: "string" }, entityId: { type: "string" } } },
  PLACE_CELL: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, remove: { type: "boolean" } } },
  ISSUE_ORDER: { type: "object", shape: { fromX: { type: "number" }, fromY: { type: "number" }, targetX: { type: "number" }, targetY: { type: "number" } } },
  ISSUE_MOVE: { type: "object", shape: { entityId: { type: "string" }, targetX: { type: "number" }, targetY: { type: "number" } } },
  PLACE_CORE: { type: "object", shape: { x: { type: "number" }, y: { type: "number" } } },
  PLACE_BUILDING: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, buildingKind: { type: "string" }, facing: { type: "string" } } },
  PLACE_BELT_SEGMENT: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, direction: { type: "string" }, remove: { type: "boolean" } } },
  PLACE_LINE_SEGMENT: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, remove: { type: "boolean" } } },
  SET_CORE_ROUTING: { type: "object", shape: { coreId: { type: "string" }, resourceKind: { type: "string" } } },
  QUEUE_WORKER: { type: "object", shape: { coreId: { type: "string" }, count: { type: "number" } } },
  SPAWN_FIGHTER: { type: "object", shape: { coreId: { type: "string" }, workerId: { type: "string" }, topologyClass: { type: "string" } } },
  ASSIGN_REPAIR: { type: "object", shape: { workerId: { type: "string" }, targetX: { type: "number" }, targetY: { type: "number" } } },
  PLACE_SPLIT_CLUSTER: { type: "object", shape: { x: { type: "number" }, y: { type: "number" } } },
  HARVEST_CELL: { type: "object", shape: { x: { type: "number" }, y: { type: "number" } } },
  HARVEST_PULSE: { type: "object", shape: {}, allowUnknown: true },
  PRUNE_CLUSTER: { type: "object", shape: {}, allowUnknown: true },
  RECYCLE_PATCH: { type: "object", shape: {}, allowUnknown: true },
  SEED_SPREAD: { type: "object", shape: {}, allowUnknown: true },
  SET_ZONE: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, radius: { type: "number" }, zoneType: { type: "number" } } },
  BUY_EVOLUTION: { type: "object", shape: { archetypeId: { type: "string" } } },
  SET_PLAYER_DOCTRINE: { type: "object", shape: { doctrineId: { type: "string" } } },
  SET_MUTATOR_PATTERN: { type: "object", shape: { mutatorId: { type: "string" } }, allowUnknown: true },
  COMMIT_MUTATION: { type: "object", shape: { mutatorId: { type: "string" }, topologyClass: { type: "string" } }, allowUnknown: true },
  SET_WIN_MODE: { type: "object", shape: { winMode: { type: "string" } } },
  SET_OVERLAY: { type: "string" },
  SET_PLACEMENT_COST: { type: "object", shape: { enabled: { type: "boolean" } } },
};
