export const actionSchema = {
  GEN_WORLD: { type: "object", shape: {} },
  CONFIRM_FOUNDATION: { type: "object", shape: {} },
  CONFIRM_CORE_ZONE: { type: "object", shape: {} },
  START_DNA_ZONE_SETUP: { type: "object", shape: {} },
  TOGGLE_DNA_ZONE_CELL: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, remove: { type: "boolean" } } },
  CONFIRM_DNA_ZONE: { type: "object", shape: {} },
  BEGIN_INFRA_BUILD: { type: "object", shape: {} },
  BUILD_INFRA_PATH: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, remove: { type: "boolean" } } },
  CONFIRM_INFRA_PATH: { type: "object", shape: {} },
  TOGGLE_RUNNING: { type: "object", shape: { running: { type: "boolean" } } },
  SIM_STEP: { type: "object", shape: {} },
  SET_SPEED: { type: "number" },
  SET_SEED: { type: "string" },
  SET_SIZE: { type: "object", shape: { w: { type: "number" }, h: { type: "number" } } },
  SET_WORLD_PRESET: { type: "object", shape: { presetId: { type: "string" } } },
  SET_RENDER_MODE: { type: "string" },
  SET_PHYSICS: { type: "object", shape: {}, allowUnknown: true },
  SET_BRUSH: { type: "object", shape: {}, allowUnknown: true },
  SET_UI: { type: "object", shape: {}, allowUnknown: true },
  SET_GLOBAL_LEARNING: { type: "object", shape: {}, allowUnknown: true },
  RESET_GLOBAL_LEARNING: { type: "object", shape: {} },
  PAINT_BRUSH: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, mode: { type: "string" }, radius: { type: "number" } } },
  PLACE_CELL: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, remove: { type: "boolean" } } },
  PLACE_SPLIT_CLUSTER: { type: "object", shape: { x: { type: "number" }, y: { type: "number" } } },
  HARVEST_CELL: { type: "object", shape: { x: { type: "number" }, y: { type: "number" } } },
  HARVEST_PULSE: { type: "object", shape: {}, allowUnknown: true },
  PRUNE_CLUSTER: { type: "object", shape: {}, allowUnknown: true },
  RECYCLE_PATCH: { type: "object", shape: {}, allowUnknown: true },
  SEED_SPREAD: { type: "object", shape: {}, allowUnknown: true },
  SET_ZONE: { type: "object", shape: { x: { type: "number" }, y: { type: "number" }, radius: { type: "number" }, zoneType: { type: "number" } } },
  BUY_EVOLUTION: { type: "object", shape: { archetypeId: { type: "string" } } },
  SET_PLAYER_DOCTRINE: { type: "object", shape: { doctrineId: { type: "string" } } },
  SET_WIN_MODE: { type: "object", shape: { winMode: { type: "string" } } },
  SET_OVERLAY: { type: "string" },
  SET_PLACEMENT_COST: { type: "object", shape: { enabled: { type: "boolean" } } },
};
