export const mutationMatrix = {
  GEN_WORLD: ["/meta/physics", "/meta/playerLineageId", "/meta/cpuLineageId", "/world/", "/world/actionMap", "/sim/"],
  TOGGLE_RUNNING: ["/sim/running"],
  SIM_STEP: ["/meta/globalLearning", "/meta/gridW", "/meta/gridH", "/world/", "/sim/"],
  SET_SPEED: ["/meta/speed"],
  SET_SEED: ["/meta/seed"],
  SET_SIZE: ["/meta/gridW", "/meta/gridH"],
  SET_RENDER_MODE: ["/meta/renderMode"],
  SET_PHYSICS: ["/meta/physics"],
  SET_BRUSH: ["/meta/brushMode", "/meta/brushRadius"],
  SET_UI: ["/meta/ui"],
  SET_GLOBAL_LEARNING: ["/meta/globalLearning", "/world/globalLearning"],
  RESET_GLOBAL_LEARNING: ["/meta/globalLearning", "/world/globalLearning", "/world/lineageMemory"],
  PAINT_BRUSH: ["/world/L", "/world/R", "/world/W", "/world/Sat"],
  PLACE_CELL: ["/world/alive", "/world/E", "/world/reserve", "/world/link", "/world/lineageId", "/world/hue", "/world/trait", "/world/age", "/world/born", "/world/died", "/world/W", "/sim/playerDNA"],
  PLACE_SPLIT_CLUSTER: ["/world/alive", "/world/E", "/world/reserve", "/world/link", "/world/lineageId", "/world/hue", "/world/trait", "/world/age", "/world/born", "/world/died", "/world/W", "/sim/playerDNA"],
  DEV_BALANCE_RUN_AI: ["/meta/devMutationVault", "/world/devMutationVault", "/world/devAiLast", "/world/lineageMemory", "/world/trait", "/world/hue"],
  APPLY_BUFFERED_SIM_STEP: ["/meta/globalLearning", "/meta/gridW", "/meta/gridH", "/world/", "/sim/"],
  HARVEST_CELL: ["/sim/playerDNA", "/sim/totalHarvested", "/sim/playerStage", "/world/alive", "/world/E"],
  SET_ZONE: ["/world/zoneMap"],
  BUY_EVOLUTION: ["/sim/playerDNA", "/world/trait", "/world/hue", "/world/lineageMemory"],
  SET_PLAYER_DOCTRINE: ["/world/lineageMemory"],
  SET_WIN_MODE: ["/sim/winMode"],
  SET_OVERLAY: ["/meta/activeOverlay"],
  SET_PLACEMENT_COST: ["/meta/placementCostEnabled"],
  RUN_BENCHMARK: [],
};
