export const mutationMatrix = {
  GEN_WORLD: ["/meta/worldPresetId", "/meta/physics", "/meta/gameMode", "/meta/playerLineageId", "/meta/cpuLineageId", "/world/", "/world/actionMap", "/sim/"],
  CONFIRM_FOUNDATION: ["/sim/runPhase", "/sim/running"],
  TOGGLE_RUNNING: ["/sim/running"],
  SIM_STEP: ["/meta/globalLearning", "/meta/gridW", "/meta/gridH", "/world/", "/sim/"],
  SET_SPEED: ["/meta/speed"],
  SET_SEED: ["/meta/seed"],
  SET_SIZE: ["/meta/gridW", "/meta/gridH"],
  SET_WORLD_PRESET: ["/meta/worldPresetId", "/meta/physics", "/meta/playerLineageId", "/meta/cpuLineageId", "/world/", "/sim/"],
  SET_RENDER_MODE: ["/meta/renderMode"],
  SET_PHYSICS: ["/meta/physics"],
  SET_BRUSH: ["/meta/brushMode", "/meta/brushRadius"],
  SET_UI: ["/meta/ui"],
  SET_GLOBAL_LEARNING: ["/meta/globalLearning", "/world/globalLearning"],
  RESET_GLOBAL_LEARNING: ["/meta/globalLearning", "/world/globalLearning", "/world/lineageMemory"],
  PAINT_BRUSH: ["/world/L", "/world/R", "/world/W", "/world/Sat"],
  PLACE_CELL: ["/world/alive", "/world/E", "/world/reserve", "/world/link", "/world/lineageId", "/world/hue", "/world/trait", "/world/age", "/world/born", "/world/died", "/world/W", "/world/founderMask", "/sim/playerDNA", "/sim/founderPlaced"],
  PLACE_SPLIT_CLUSTER: ["/world/alive", "/world/E", "/world/reserve", "/world/link", "/world/lineageId", "/world/hue", "/world/trait", "/world/age", "/world/born", "/world/died", "/world/W", "/sim/playerDNA"],
  DEV_BALANCE_RUN_AI: ["/meta/devMutationVault", "/world/devMutationVault", "/world/devAiLast", "/world/lineageMemory", "/world/trait", "/world/hue"],
  APPLY_BUFFERED_SIM_STEP: ["/meta/globalLearning", "/meta/gridW", "/meta/gridH", "/world/", "/sim/"],
  HARVEST_CELL: ["/sim/playerDNA", "/sim/totalHarvested", "/world/alive", "/world/E"],
  HARVEST_PULSE: ["/world/P", "/world/R", "/world/Sat", "/world/lineageMemory", "/sim/playerDNA", "/sim/harvestYieldTotal", "/sim/meanWaterField", "/sim/stabilityScore", "/sim/ecologyScore", "/sim/stageProgressScore", "/sim/activeBiomeCount", "/sim/playerStage"],
  PRUNE_CLUSTER: ["/world/P", "/world/W", "/world/lineageMemory", "/sim/playerDNA", "/sim/pruneYieldTotal", "/sim/meanWaterField", "/sim/stabilityScore", "/sim/ecologyScore", "/sim/stageProgressScore", "/sim/activeBiomeCount", "/sim/playerStage"],
  RECYCLE_PATCH: ["/world/W", "/world/R", "/world/Sat", "/world/lineageMemory", "/sim/playerDNA", "/sim/recycleYieldTotal", "/sim/meanWaterField", "/sim/stabilityScore", "/sim/ecologyScore", "/sim/stageProgressScore", "/sim/activeBiomeCount", "/sim/playerStage"],
  SEED_SPREAD: ["/world/P", "/world/R", "/world/B", "/world/lineageMemory", "/sim/playerDNA", "/sim/seedYieldTotal", "/sim/meanWaterField", "/sim/stabilityScore", "/sim/ecologyScore", "/sim/stageProgressScore", "/sim/activeBiomeCount", "/sim/playerStage"],
  SET_ZONE: ["/world/zoneMap"],
  BUY_EVOLUTION: ["/sim/playerDNA", "/world/trait", "/world/hue", "/world/lineageMemory"],
  SET_PLAYER_DOCTRINE: ["/world/lineageMemory"],
  SET_WIN_MODE: ["/sim/winMode"],
  SET_OVERLAY: ["/meta/activeOverlay"],
  SET_PLACEMENT_COST: ["/meta/placementCostEnabled"],
  RUN_BENCHMARK: [],
};
