const SIM_BOOLEAN_KEYS = Object.freeze([
  "running",
  "zone2Unlocked",
  "dnaZoneCommitted",
  "infrastructureUnlocked",
]);

const SIM_STRING_KEYS = Object.freeze([
  "gameResult",
  "winMode",
  "goal",
  "runPhase",
  "nextZoneUnlockKind",
  "infraBuildMode",
]);

const SIM_OBJECT_KEYS = Object.freeze([
  "patternCatalog",
  "patternBonuses",
  "cellPatternCounts",
  "runSummary",
]);

export const simGate = {
  limits: {
    maxPatches: 5000,
    maxTiles: 250000,
  },
  world: {
    traitCount: 7,
    keys: {
      w: { type: "number" },
      h: { type: "number" },
      nextLineageId: { type: "number" },
      alive: { type: "ta", ctor: "Uint8Array", len: "N" },
      E: { type: "ta", ctor: "Float32Array", len: "N" },
      L: { type: "ta", ctor: "Float32Array", len: "N" },
      R: { type: "ta", ctor: "Float32Array", len: "N" },
      W: { type: "ta", ctor: "Float32Array", len: "N" },
      water: { type: "ta", ctor: "Float32Array", len: "N" },
      Sat: { type: "ta", ctor: "Float32Array", len: "N" },
      baseSat: { type: "ta", ctor: "Float32Array", len: "N" },
      P: { type: "ta", ctor: "Float32Array", len: "N" },
      B: { type: "ta", ctor: "Float32Array", len: "N" },
      plantKind: { type: "ta", ctor: "Int8Array", len: "N" },
      reserve: { type: "ta", ctor: "Float32Array", len: "N" },
      link: { type: "ta", ctor: "Float32Array", len: "N" },
      superId: { type: "ta", ctor: "Int32Array", len: "N" },
      clusterField: { type: "ta", ctor: "Float32Array", len: "N" },
      hue: { type: "ta", ctor: "Float32Array", len: "N" },
      lineageId: { type: "ta", ctor: "Uint32Array", len: "N" },
      trait: { type: "ta", ctor: "Float32Array", len: "N*TRAIT_COUNT" },
      age: { type: "ta", ctor: "Uint16Array", len: "N" },
      born: { type: "ta", ctor: "Uint8Array", len: "N" },
      died: { type: "ta", ctor: "Uint8Array", len: "N" },
      biomeId: { type: "ta", ctor: "Int8Array", len: "N" },
      actionMap: { type: "ta", ctor: "Uint8Array", len: "N" },
      balanceGovernor: { type: "object" },
      lastFounderTick: { type: "number" },
      globalLearning: { type: "object" },
      devMutationVault: { type: "object" },
      lineageMemory: { type: "object" },
      lineageThreatMemory: { type: "object" },
      lineageDefenseReadiness: { type: "object" },
      clusterAttackState: { type: "object" },
      zoneMap: { type: "ta", ctor: "Int8Array", len: "N" },
      zoneRole: { type: "ta", ctor: "Int8Array", len: "N" },
      zoneId: { type: "ta", ctor: "Uint16Array", len: "N" },
      zoneMeta: { type: "object" },
      coreZoneMask: { type: "ta", ctor: "Uint8Array", len: "N" },
      dnaZoneMask: { type: "ta", ctor: "Uint8Array", len: "N" },
      infraCandidateMask: { type: "ta", ctor: "Uint8Array", len: "N" },
      founderMask: { type: "ta", ctor: "Uint8Array", len: "N" },
      visibility: { type: "ta", ctor: "Uint8Array", len: "N" },
      explored: { type: "ta", ctor: "Uint8Array", len: "N" },
    },
  },
  sim: {
    keys: [
      "tick", "running", "runPhase", "founderBudget", "founderPlaced", "unlockedZoneTier", "nextZoneUnlockKind", "nextZoneUnlockCostEnergy", "zoneUnlockProgress", "coreEnergyStableTicks", "zone2Unlocked", "zone2PlacementBudget", "dnaZoneCommitted", "nextInfraUnlockCostDNA", "infrastructureUnlocked", "infraBuildMode", "infraBuildCostEnergy", "infraBuildCostDNA", "cpuBootstrapDone", "patternCatalog", "patternBonuses", "aliveCount", "aliveRatio", "meanLAlive", "meanEnergyAlive", "meanReserveAlive",
      "meanNutrientField", "meanToxinField", "meanSaturationField", "meanPlantField", "meanBiochargeField", "meanWaterField",
      "plantTileRatio", "dominantHueRatio", "lineageDiversity", "evolutionStageMean", "evolutionStageMax",
      "networkRatio", "clusterRatio", "birthsLastStep", "deathsLastStep", "mutationsLastStep",
      "raidEventsLastStep", "infectionsLastStep", "conflictKillsLastStep", "superCellsLastStep",
      "remoteAttacksLastStep", "remoteAttackKillsLastStep", "defenseActivationsLastStep", "resourceStolenLastStep",
      "plantsPrunedLastStep", "cellPatternCounts", "nutrientCappedTilesLastStep", "energyClearedTilesLastStep",
      "expansionCount", "lastExpandTick", "expansionWork", "nextExpandCost",
      "playerAliveCount", "cpuAliveCount", "playerEnergyIn", "playerEnergyOut",
      "playerEnergyNet", "playerEnergyStored", "lightShare", "nutrientShare", "seasonPhase",
      "playerDNA", "totalHarvested", "playerStage", "stageProgressScore",
      "harvestYieldTotal", "pruneYieldTotal", "recycleYieldTotal", "seedYieldTotal",
      "stabilityScore", "ecologyScore", "activeBiomeCount", "patternCatalog", "patternBonuses",
      "energySupremacyTicks", "efficiencyTicks", "lossStreakTicks", "stockpileTicks",
      "cpuEnergyIn", "gameResult", "winMode", "gameEndTick", "runSummary", "goal",
    ],
    booleanKeys: SIM_BOOLEAN_KEYS,
    stringKeys: SIM_STRING_KEYS,
    objectKeys: SIM_OBJECT_KEYS,
  },
};
