import {
  BRUSH_MODE,
  GAME_MODE,
  GAME_RESULT,
  GOAL_CODE,
  OVERLAY_MODE,
  RUN_PHASE,
  WIN_MODE,
} from "../../game/contracts/ids.js";

export const stateSchema = {
  type: "object",
  shape: {
    meta: {
      type: "object",
      shape: {
        seed: { type: "string", default: "life-light" },
        gridW: { type: "number", default: 16 },
        gridH: { type: "number", default: 16 },
        speed: { type: "number", default: 2 },
        brushMode: { type: "string", default: BRUSH_MODE.OBSERVE },
        brushRadius: { type: "number", default: 3 },
        renderMode: { type: "string", default: "combined" },
        activeOverlay: { type: "string", default: OVERLAY_MODE.NONE },
        worldPresetId: { type: "string", default: "river_delta" },
        gameMode: { type: "string", default: GAME_MODE.GENESIS },
        physics: { type: "object", shape: {}, allowUnknown: true },
        ui: {
          type: "object",
          shape: {
            panelOpen: { type: "boolean", default: false },
            activeTab: { type: "string", default: "lage" },
            expertMode: { type: "boolean", default: false },
            showBiochargeOverlay: { type: "boolean", default: false },
            showRemoteAttackOverlay: { type: "boolean", default: true },
            showDefenseOverlay: { type: "boolean", default: true },
            offscreenEnabled: { type: "boolean", default: false },
            renderDetailMode: { type: "string", default: "auto" },
            ariaLevel: { type: "number", default: 1 },
          },
        },
        globalLearning: {
          type: "object",
          default: {
            enabled: false,
            strength: 0.42,
            bank: {
              light: 0.5,
              nutrient: 0.5,
              toxin: 0.5,
              resilience: 0.5,
              energySense: 0.5,
              toxinMetabolism: 0.0,
              stage: 1,
              xp: 0,
              mutationScore: 0,
              samples: 0,
              updates: 0,
            },
          },
          shape: {},
          allowUnknown: true,
        },
        devMutationVault: { type: "object", shape: {}, allowUnknown: true },
        playerLineageId: { type: "number", default: 0 },
        cpuLineageId: { type: "number", default: 0 },
        placementCostEnabled: { type: "boolean", default: true },
      },
    },
    world: { type: "object", shape: {}, allowUnknown: true },
    sim: {
      type: "object",
      shape: {
        tick: { type: "number", default: 0 },
        running: { type: "boolean", default: false },
        runPhase: { type: "string", default: RUN_PHASE.GENESIS_SETUP },
        founderBudget: { type: "number", default: 4 },
        founderPlaced: { type: "number", default: 0 },
        unlockedZoneTier: { type: "number", default: 0 },
        nextZoneUnlockKind: { type: "string", default: "" },
        nextZoneUnlockCostEnergy: { type: "number", default: 0 },
        zoneUnlockProgress: { type: "number", default: 0 },
        coreEnergyStableTicks: { type: "number", default: 0 },
        zone2Unlocked: { type: "boolean", default: false },
        zone2PlacementBudget: { type: "number", default: 0 },
        dnaZoneCommitted: { type: "boolean", default: false },
        nextInfraUnlockCostDNA: { type: "number", default: 0 },
        infrastructureUnlocked: { type: "boolean", default: false },
        infraBuildMode: { type: "string", default: "" },
        infraBuildCostEnergy: { type: "number", default: 0 },
        infraBuildCostDNA: { type: "number", default: 0 },
        cpuBootstrapDone: { type: "number", default: 0 },
        aliveCount: { type: "number", default: 0 },
        aliveRatio: { type: "number", default: 0 },
        meanLAlive: { type: "number", default: 0 },
        meanEnergyAlive: { type: "number", default: 0 },
        meanReserveAlive: { type: "number", default: 0 },
        meanNutrientField: { type: "number", default: 0 },
        meanToxinField: { type: "number", default: 0 },
        meanSaturationField: { type: "number", default: 0 },
        meanPlantField: { type: "number", default: 0 },
        meanBiochargeField: { type: "number", default: 0 },
        meanWaterField: { type: "number", default: 0 },
        plantTileRatio: { type: "number", default: 0 },
        dominantHueRatio: { type: "number", default: 0 },
        lineageDiversity: { type: "number", default: 0 },
        evolutionStageMean: { type: "number", default: 1 },
        evolutionStageMax: { type: "number", default: 1 },
        networkRatio: { type: "number", default: 0 },
        clusterRatio: { type: "number", default: 0 },
        birthsLastStep: { type: "number", default: 0 },
        deathsLastStep: { type: "number", default: 0 },
        mutationsLastStep: { type: "number", default: 0 },
        raidEventsLastStep: { type: "number", default: 0 },
        infectionsLastStep: { type: "number", default: 0 },
        conflictKillsLastStep: { type: "number", default: 0 },
        superCellsLastStep: { type: "number", default: 0 },
        remoteAttacksLastStep: { type: "number", default: 0 },
        remoteAttackKillsLastStep: { type: "number", default: 0 },
        defenseActivationsLastStep: { type: "number", default: 0 },
        resourceStolenLastStep: { type: "number", default: 0 },
        plantsPrunedLastStep: { type: "number", default: 0 },
        nutrientCappedTilesLastStep: { type: "number", default: 0 },
        energyClearedTilesLastStep: { type: "number", default: 0 },
        expansionCount: { type: "number", default: 0 },
        lastExpandTick: { type: "number", default: -99999 },
        expansionWork: { type: "number", default: 0 },
        nextExpandCost: { type: "number", default: 120 },
        playerAliveCount: { type: "number", default: 0 },
        cpuAliveCount: { type: "number", default: 0 },
        playerEnergyIn: { type: "number", default: 0 },
        playerEnergyOut: { type: "number", default: 0 },
        playerEnergyNet: { type: "number", default: 0 },
        playerEnergyStored: { type: "number", default: 0 },
        lightShare: { type: "number", default: 0 },
        nutrientShare: { type: "number", default: 0 },
        seasonPhase: { type: "number", default: 0 },
        playerDNA: { type: "number", default: 0 },
        totalHarvested: { type: "number", default: 0 },
        playerStage: { type: "number", default: 1 },
        stageProgressScore: { type: "number", default: 0 },
        harvestYieldTotal: { type: "number", default: 0 },
        pruneYieldTotal: { type: "number", default: 0 },
        recycleYieldTotal: { type: "number", default: 0 },
        seedYieldTotal: { type: "number", default: 0 },
        stabilityScore: { type: "number", default: 0 },
        ecologyScore: { type: "number", default: 0 },
        activeBiomeCount: { type: "number", default: 0 },
        patternCatalog: { type: "object", default: {}, shape: {}, allowUnknown: true },
        patternBonuses: {
          type: "object",
          default: {
            energy: 0,
            dna: 0,
            stability: 0,
            vision: 0,
            defense: 0,
            transport: 0,
          },
          shape: {},
          allowUnknown: true,
        },
        energySupremacyTicks: { type: "number", default: 0 },
        efficiencyTicks: { type: "number", default: 0 },
        lossStreakTicks: { type: "number", default: 0 },
        stockpileTicks: { type: "number", default: 0 },
        cpuEnergyIn: { type: "number", default: 0 },
        gameResult: { type: "string", default: GAME_RESULT.NONE },
        winMode: { type: "string", default: WIN_MODE.SUPREMACY },
        gameEndTick: { type: "number", default: 0 },
        goal: { type: "string", default: GOAL_CODE.HARVEST_SECURE },
      },
    },
  },
};
